ARG PHP_MAJOR_VERSION
ARG PHP_MINOR_VERSION
FROM datadog/dd-trace-ci:php-compile-extension-alpine-${PHP_MAJOR_VERSION}.${PHP_MINOR_VERSION} as trace-build

RUN mkdir /trace
COPY . /trace/

RUN cd /trace && build-dd-trace-php

FROM scratch
COPY --from=trace-build /trace/tmp/build_extension/.libs/ddtrace.so /opt/ddtrace.so
